#!/bin/bash
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
[ -z "$(find -H /var/lib/apt/lists -maxdepth 0 -mtime -7)" ] && sudo apt update
function fancy_message() {
    if [ -z "${1}" ] || [ -z "${2}" ]; then
      return
    fi
    local RED="\e[31m"
    local GREEN="\e[32m"
    local YELLOW="\e[33m"
    local RESET="\e[0m"
    local MESSAGE_TYPE=""
    local MESSAGE=""
    MESSAGE_TYPE="${1}"
    MESSAGE="${2}"
    case ${MESSAGE_TYPE} in
      info) echo -e "[${GREEN}+${RESET}] INFO: ${MESSAGE}";;
      warn) echo -e "[${YELLOW}*${RESET}] WARNING: ${MESSAGE}";;
      error) echo -e "[${RED}!${RESET}] ERROR: ${MESSAGE}";;
      *) echo -e "[?] UNKNOWN: ${MESSAGE}";;
    esac
}
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo " "
      echo "options:"
      echo "-I --install, Installs package"
      echo "-S --search, Search for package"
      echo "-R --remove, Removes package"
      echo "-C --change-repo, Chooses repo"
      echo "-U --update, Update script"
      echo "-V --version, Prints pacstall version"
      echo "-L --list, Lists installed packages"
      echo " "
      exit 0
      ;;
    -I|--install)
      RED='\033[0;31m'
      CYAN='\033[0;36m'
      NC='\033[0m'
      GREEN='\033[0;32m'
      PURPLE='\033[0;35m'
      YELLOW='\033[1;33m'
      BLUE='\033[0;34m'
      export LC_ALL=C
      function trap_ctrlc ()
      {
	  fancy_message warn "the installation of $2 was interrupted, removing files"
	  rm -rf /tmp/pacstall/*
          exit 2
      }
      trap "trap_ctrlc" 2
      if [ "$EUID" -ne 0 ]; then 
      fancy_message error "Run as root"
      exit 1
      fi
      PACPREFIX="apt install -y "
      PACKAGE=$2
      if [[ -z "$PACKAGE" ]]; then
        fancy_message error "You failed to specify a package"
        exit 1
      fi
      if [[ ! -e /usr/share/pacstall/repo/ ]]; then
          mkdir -p /usr/share/pacstall/repo
          touch /usr/share/pacstall/repo/pacstallrepo.txt
	  sudo pacstall -C
      fi
      REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
      export HOMEDIR=$HOME
      INPUT=$2
      INSTALLING=1
      echo $INPUT > /tmp/pacstalling
      if grep -q @ /tmp/pacstalling; then
          export PACKAGE=$(cut -d@ -f1 /tmp/pacstalling)
          export REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
          export URL="https://raw.githubusercontent.com/$REPO/master/packages/$PACKAGE/$(cat /tmp/pacstalling).pacscript"
          source /usr/share/pacstall/scripts/download.sh
      else
          export PACKAGE=$INPUT
          export REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
          export URL="https://raw.githubusercontent.com/$REPO/master/packages/$PACKAGE/$PACKAGE.pacscript"
          source /usr/share/pacstall/scripts/download.sh
          exit
      fi   
      ;;
    -Il|--install-local)
      REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt) 
      INPUT=$2
      # If input is relative and ends in .pacscript
      if [[ $INPUT == *".pacscript" ]]; then
        PACKAGE=${INPUT%.pacscript}
      else
        # If input is a full path
        if [[ $(echo ${INPUT:0:1}) == *\/* ]]; then
          DIR=$(echo $INPUT | sed 's|\(.*\)/.*|\1|')
          cd $DIR
          INPUT=${INPUT%.pacscript}
          PACKAGE=$(echo $INPUT | sed 's|.*/||')
        else
          # If input doesn't end in .pacscript and is relative
          if [[ $INPUT != *".pacscript" ]]; then
            PACKAGE=$INPUT
          fi
        fi
      fi
      source /usr/share/pacstall/scripts/install-local.sh
      exit
      ;;
    -S|--search)
      source /usr/share/pacstall/scripts/search.sh
      ;;
    -R|--remove)
      PACKAGE=$2
      if test -f "/var/lib/porg/$PACKAGE"; then
        sudo rm $(cat /var/lib/porg/$PACKAGE | sed -n 's/|\(.*\)//;/^#\(.*\)/d;p')
        sudo rm -rf /var/log/pacstall_installed/$PACKAGE.pacscript
        sudo rm /var/lib/porg/$PACKAGE
        sudo rm /var/log/pacstall_installed/$PACKAGE*
        fancy_message info "Done removing $PACKAGE"
        exit
      else
        fancy_message error "$PACKAGE does not exist"
        exit 1
      fi
      ;;
    -C|--change-repo)
      if [[ -z "$2" ]]; then
      . /usr/share/pacstall/scripts/change-repo.sh
      else
      echo "$2" | sudo tee /usr/share/pacstall/repo/pacstallrepo.txt >/dev/null 2>&1
      exit
      fi
      ;;
    -V|--version)
      if [[ -z "$2" ]]; then
        COLOR='\e[1;36m'
        NC='\033[0m'
        echo -e "1.0.4 ${COLOR}Celeste${NC}"
        exit 0
      else
        echo $(pacstall -L | grep '$2' | cut -d' ' -f2-)
      fi
      ;;
    -U|--update)
      for i in {change-repo.sh,search.sh,download.sh,install-local.sh}; do
        sudo wget -q -N https://raw.githubusercontent.com/Henryws/pacstall/master/misc/scripts/$i -P /usr/share/pacstall/scripts 2>/dev/null 
      done
      sudo wget -q -N https://raw.githubusercontent.com/Henryws/pacstall/master/pacstall -P /bin 2>/dev/null
      fancy_message info "You are at version $(pacstall -V)"
      exit 0
      ;;
    -Ud|--update-dev)
      UPDATEBRANCH=1.0.4-Celeste
      fancy_message warn "You may experience severe bugs"
      printf "Do you want to continue? [y/N] "
      read -r input
      if [[ $input = y ]]; then
        sudo pacstall -U
        sudo sed -i 's/master/'"$UPDATEBRANCH"'/g' /bin/pacstall
        exit
      else
        exit
      fi
      ;;
    -L|--list)
      /bin/ls -1 --color=auto /var/log/pacstall_installed | tr '-' ' '
      exit
      ;;
    -D|--download)
      PACKAGE=$2
      if [[ -z "$PACKAGE" ]]; then
        fancy_message error "You failed to specify a package"
        exit 1
      fi
      INSTALLING=0
      REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
      source /usr/share/pacstall/scripts/download.sh
      exit
      ;;
    -Ra|--remove-all)
      PACKAGE=$*
      for i in $PACKAGE ; do
        if [ -f /var/log/pacstall_installed/$i ] ; then
          LOCATION=installed
        else
          if [ -f /var/log/pacstall_orphaned/$i ] ; then
            LOCATION=orphaned
          fi
        fi
        source /var/log/pacstall_$lOCATION/$i.pacscript
        sudo apt remove $depends
        sudo pacstall -R $i
        rm -rf /var/log/pacstall_$LOCATION/$i.pacscript
      done
      ;;
    -Qd|--query-depends)
      PACKAGE=$2
      REPO=$(cat /usr/share/pacstall/repo/pacstallrepo.txt)
      URL="https://raw.githubusercontent.com/$REPO/master/packages/$PACKAGE/$PACKAGE.pacscript"
      if [[ -z "$PACKAGE" ]]; then
          fancy_message error "You failed to specify a package"
          exit 1
      fi
      if curl --output /dev/null --silent --head --fail "$URL"; then
          source <(curl -s $URL) >/dev/null 2>&1
      else
          fancy_message error "$PACKAGE doesn't seem to exist"
          exit 1
      fi
      echo "build_depends=\"$build_depends\""
      echo "depends=\"$depends\""
      exit
      ;;
     *)
      pacstall -h
      exit 1
      ;;
  esac
done
