name: Bug report
description: Create a report to help us improve
labels: ["bug", "triage"]
assignees:
  - wizard-28
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: Tell us what happened!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To reproduce
      placeholder: 1. Just explain what happened and where you think the issue is.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
    validations:
          required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: Attach or link to screenshots here.
    validations:
          required: true
  - type: input
    id: os
    attributes:
      label: OS version
      description: Provide your OS version.
      placeholder: Ubuntu 20.04
    validations:
      required: true
  - type: input
    id: pacstall
    attributes:
      label: Pacstall version
      description: Provide the installed pacstall version.
      placeholder: 1.7.2, master branch
    validations:
      required: true
