name: Feature request
description: Suggest an idea for Pacstall
labels: ["enhancement", "triage"]
assignees:
  - Henryws
  - wizard-28
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: A clear and concise description of what you want to happen.
    validations:
          required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
