#!/bin/bash
#     ____                  __        ____
#    / __ \____ ___________/ /_____ _/ / /
#   / /_/ / __ `/ ___/ ___/ __/ __ `/ / /
#  / ____/ /_/ / /__(__  ) /_/ /_/ / / /
# /_/    \__,_/\___/____/\__/\__,_/_/_/
#
# Copyright (C) 2020-2021
#
# This file is part of Pacstall
#
# Pacstall is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License
#
# Pacstall is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pacstall. If not, see <https://www.gnu.org/licenses/>.

packages="$(compgen -W "$(sed -e 's/$/\/packagelist/' /usr/share/pacstall/repo/pacstallrepo.txt | xargs -n 1 curl -s | awk '!seen[$0]++')" -- "$cur")"

_pacstall() {
	cur=${COMP_WORDS[COMP_CWORD]}
	prev=${COMP_WORDS[COMP_CWORD-1]}

	case "$prev" in
		-'?'|--help|-v|--version)
			return
		;;

		-S|--search)
			COMPREPLY=($packages)
			return
		;;

		-I|--install)
			COMPREPLY=($packages)
			return
		;;

		-R|--remove)
			COMPREPLY=( $( compgen -W "$(\ls -1aA /var/log/pacstall/metadata)" -- $cur ) )
			return
		;;

		-Qi|--query-info)
			COMPREPLY=( $( compgen -W "$(\ls -1aAp /var/log/pacstall/metadata)" -- $cur ) )
			return
		;;
		-Il|--install-local)
			COMPREPLY=( $( compgen -W "$(find -- *.pacscript* 2>/dev/null | sed 's/.pacscript//g')" -- "$cur" ) )
			return
		;;

		-D|--download)
			COMPREPLY=($packages)
			return
		;;

		-PS)
			COMPREPLY=($packages)
			return
		;;

		-PI)
			COMPREPLY=($packages)
			return
		;;

		-PQi)
			COMPREPLY=( $( compgen -W "$(\ls -1aAp /var/log/pacstall/metadata)" -- $cur ) )
			return
		;;
		-PIl)
			COMPREPLY=( $( compgen -W "$(find -- *.pacscript* 2>/dev/null | sed 's/.pacscript//g')" -- "$cur" ) )
			return
		;;

		-PD)
			COMPREPLY=($packages)
			return
		;;
	esac

	case "$cur" in
		--*)
			COMPREPLY=( $( compgen -W '$( _parse_help "$1" )' -- "$cur" ) )
			return
		;;
		*)
			COMPREPLY=( $( compgen -W "-I -S -R -A -U -V -L -Up -Qi -T" "$cur" ) )
			return
		;;
	esac
} && complete -o filenames -o bashdefault -F _pacstall pacstall
# vim:set ft=sh ts=4 sw=4 noet:
