#!/usr/bin/env fish

#     ____                  __        ____
#    / __ \____ ___________/ /_____ _/ / /
#   / /_/ / __ `/ ___/ ___/ __/ __ `/ / /
#  / ____/ /_/ / /__(__  ) /_/ /_/ / / /
# /_/    \__,_/\___/____/\__/\__,_/_/_/
#
# Copyright (C) 2020-2021
#
# This file is part of Pacstall
#
# Pacstall is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License
#
# Pacstall is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pacstall. If not, see <https://www.gnu.org/licenses/>.
set packages (sed -e 's/$/\/packagelist/' /usr/share/pacstall/repo/pacstallrepo.txt | xargs -n 1 curl -s | awk '!seen[$0]++')

# Flag lists
set -l pacstall_commands -I --install -PI -IP -Il --install-local -PIl -IlP -S --search -R -PR -RP --remove -A --add-repo -U --update -V --version -L --list -Up -PUp -UpP --upgradee -Qi --query-info -D --download -T --tree -P --disable-prompts -K --keep -PK -PI -PIl -PR -PUp -PKI -PKIl -PKUp -KP -KI -KIl -KR -KUp -KPI -KPIl -KPUp
set -l pacstall_p_commands -I --install -Il --install-local -R --remove -Up --upgrade
set -l pacstall_p -P --disable-prompts 
set -l pacstall_k -K --keep
set -l pacstall_k_commands -I --install -Il --install-local -Up --upgrade

# Completion for normal commands
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o S -l search -d 'Search for package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o A -l add-repo -d 'Add repository'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o U -l update -d 'Update pacstall scripts'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o V -l version -d 'Print pacstall version'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o L -l list -d 'List packages installed'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o D -l download -d 'Downloads package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o T -l tree -d 'Makes a tree of a package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o Qi -l query-info -d 'Get package info'

complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o I -l install -d 'Install package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o R -l remove -d 'Remove package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o Il -l install-local -d 'Install local package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -o Up -l upgrade -d 'Upgrade packages'

complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_k_commands" -o K -l keep -d 'Retain build directory'

# Completions for P commands

complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PI -d 'Install package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PR -d 'Remove package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PIl -d 'Install local package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PUp -d 'Upgrade packages'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PK -d 'Retain build dir'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PKI -d 'Install package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PKIl -d 'Install local package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PKUp -d 'Upgrade packages'

complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o I -l install -d 'Install package'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o R -l remove -d 'Remove package'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o Il -l install-local  -d 'Install local package'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o Up  -l upgrade -d 'Upgrade packages'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o KI -l install -d 'Install package'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o KIl -l install-local  -d 'Install local package'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o KUp  -l upgrade -d 'Upgrade packages'

complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p_commands && not __fish_seen_subcommand_from $pacstall_p" -s P -l disable-prompts -d 'Disable prompts'

# Completions for K commands 

complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -KI -d 'Install package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -KIl -d 'Install local package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -KUp -d 'Upgrade packages'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -KP -d 'Disable prompts'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -KPI -d 'Install package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -KPIl -d 'Install local package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -KPUp -d 'Upgrade packages'

complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o I -l install -d 'Install package'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o Il -l install-local  -d 'Install local package'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o Up  -l upgrade -d 'Upgrade packages'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o PI -l install -d 'Install package'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o PIl -l install-local  -d 'Install local package'
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_p && not __fish_seen_subcommand_from $pacstall_p_commands" -o PUp  -l upgrade -d 'Upgrade packages'

complete -f --command pacstall -n "__fish_seen_subcommand_from $pacstall_k_commands && not __fish_seen_subcommand_from $pacstall_k" -s K -l keep -d 'Retain build dir'

# Command type lists
set -l package_commands -I -PI -IP --install -S --search -D --download -KI -IK -KPI -KIP -PKI -PIK -IKP -IPK
set -l log_commands -R -PR -RP --remove -L --list -Qi --query-info -T --tree
set -l pacscript_commands -Il -PIl -IlP --install-local -KIl -IlK -PKIl -PIlK -KIlP -KPIl -IlKP -IlPK

# Completion for the package related flags
complete -f --command pacstall -n "__fish_seen_subcommand_from $package_commands" -a "$packages"

# Completion for the log related flags
complete -f --command pacstall -n "__fish_seen_subcommand_from $log_commands" -a "(\ls -1aA /var/log/pacstall/metadata | tr ' ' '\n')"

# Completion for the local pacscript flags
complete -f --command pacstall -n "__fish_seen_subcommand_from $pacscript_commands" -a "(find -maxdepth 1 -type f -name '*.pacscript' | sed 's/.pacscript//g' | sed 's/.\///g')"

# vim:set ft=sh ts=4 sw=4 noet:
