#!/usr/bin/env fish

#     ____                  __        ____
#    / __ \____ ___________/ /_____ _/ / /
#   / /_/ / __ `/ ___/ ___/ __/ __ `/ / /
#  / ____/ /_/ / /__(__  ) /_/ /_/ / / /
# /_/    \__,_/\___/____/\__/\__,_/_/_/
#
# Copyright (C) 2020-2021
#
# This file is part of Pacstall
#
# Pacstall is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License
#
# Pacstall is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pacstall. If not, see <https://www.gnu.org/licenses/>.
set packages (sed -e 's/$/\/packagelist/' /usr/share/pacstall/repo/pacstallrepo.txt | xargs -n 1 curl -s | awk '!seen[$0]++')

set -l pacstall_commands -I -Il -S -R -A -U -V -L -Up -Qi -D -T -PI -PIl -PR -PUp -P
set -l pacstall_p_commands -I -Il -R -Up

complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -I -d 'Install package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -Il -d 'Install local package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -S -d 'Search for package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -R -d 'Remove package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -A -d 'Add repository'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -U -d 'Update pacstall scripts'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -V -d 'Print pacstall version'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -L -d 'List packages installed'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -Up -d 'Upgrade packages'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -Qi -d 'Get package info'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -D -d 'Downloads package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -T -d 'Makes a tree of a package'

complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PI -d 'Install package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PIl -d 'Install local package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PR -d 'Remove package'
complete -f --command pacstall -n "not __fish_seen_subcommand_from $pacstall_commands" -a -PUp -d 'Upgrade packages'

complete -f --command pacstall -n "__fish_seen_subcommand_from -P && not __fish_seen_subcommand_from $pacstall_p_commands" -a -I -d 'Install package'
complete -f --command pacstall -n "__fish_seen_subcommand_from -P && not __fish_seen_subcommand_from $pacstall_p_commands" -a -Il -d 'Install local package'
complete -f --command pacstall -n "__fish_seen_subcommand_from -P && not __fish_seen_subcommand_from $pacstall_p_commands" -a -R -d 'Remove package'
complete -f --command pacstall -n "__fish_seen_subcommand_from -P && not __fish_seen_subcommand_from $pacstall_p_commands" -a -Up -d 'Upgrade package'

# Completion for the -I flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -I" -a "$packages"

# Completion for the -S flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -S" -a "$packages"

# Completion for the -R flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -R" -a "(\ls -1aA /var/log/pacstall/metadata | tr ' ' '\n')"

# Completion for the -Qi flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -Qi" -a "(\ls -1aA /var/log/pacstall/metadata | tr ' ' '\n')"

# Completion for the -D flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -D" -a "$packages"

# Completion for the -Il flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -Il" -a "(find -- *.pacscript* | sed 's/.pacscript//g')"

# Completion for the -T flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -T" -a "(\ls -1aA /var/log/pacstall/metadata | tr ' ' '\n')"

# Completion for the -PI flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -PI" -a "$packages"

# Completion for the -PR flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -PR" -a "(\ls -1aA /var/log/pacstall/metadata | tr ' ' '\n')"

# Completion for the -PIl flag
complete -f --command pacstall -n "__fish_seen_subcommand_from -PIl" -a "(find -- *.pacscript* | sed 's/.pacscript//g')"

# vim:set ft=sh ts=4 sw=4 noet:
