name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for taking the time to help make my project better! I will try to help as soon as I can'' first issue'
        pr-message: 'Thanks for making a pull request! Make sure to read my informative guide on contributing'' first pr'
