name: test install script
on: [pull_request]

env:
  LOGNAME: "pacstall"
  PACSTALL_SKIP_NETWORK_CHECK: 1
  TERM: "xterm"

  METADIR: "/var/log/pacstall/metadata"
  LOGDIR: "/var/log/pacstall/error_log"
  SCRIPTDIR: "/usr/share/pacstall"
  PACDIR: "/tmp/pacstall"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install curl sudo git wget bc -y -qq
      - name: Setup pacstall
        run: |
          echo "N" | sudo bash -c "$(curl -fsSL https://git.io/JsADh || wget -q https://git.io/JsADh -O -)"
          sudo pacstall -U . || exit 1
      - name: Run tests
        run: |
          echo "Installing neofetch"
          sudo pacstall -PI neofetch
          if [[ $? -ne 0 ]]; then
            echo "Something went wrong"
            exit 1
          fi
          echo "Installing deb package"
          sudo pacstall -PI brave-browser-beta-deb
          if [[ $? -ne 0 ]]; then
            echo "Something went wrong"
            exit 1
          fi
          echo "Testing removal"
          sudo pacstall -PR neofetch
          if [[ $? -ne 0 ]]; then
            echo "Something went wrong"
            exit 1
          fi

